name: Build and Push Container Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    
    - name: Registry Login
      run: echo "${{secrets.GITHUB_TOKEN}}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
    
    - name: Build Image
      run: docker build -f Containerfile -t ghcr.io/martindg/torism .
      
    - name: Push Image
      run: docker push ghcr.io/martindg/torism
