name: OCI Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Registry Login
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} quay.io
    
    - name: Build Image
      run: docker build -f Containerfile -t torism
      
    - name: Push Image
      run: docker push torism quay.io/martindg/torism
