name: OCI Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Registry Login
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin quay.io
    
    - name: Build Image
      run: docker build -f Containerfile -t quay.io/martindg/torism .
      
    - name: Push Image
      run: docker push quay.io/martindg/torism
